sudo: required
dist: zesty
group: edge

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.55-all-dev

script:
  - phpize
  - ./configure
  - make
  - sudo make install